### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by ranchu1**

### CODE REVIEW

**Comment by srichers** [comment]
It looks to me like one of the commits on July 20 makes a few functions non-public, which breaks me compiling my montecarlo setup with thornado/interface_flash

Error: Symbol ‘loginterpolatesinglevariable_1d3d’ referenced at (1) not found in module ‘wlinterpolationmodule’                                                                                                 ../..//Modules/Opacities/OpacityModule_TABLE.F90:16:45:                                                                                                                                                            16 |     LogInterpolateSingleVariable_1D3D_Custom, &                                                       |                                             1                                                   Error: Symbol ‘loginterpolatesinglevariable_2d2d’ referenced at (1) not found in module ‘wlinterpolationmodule’                                                                                                 make: *** [Makefile:158: OpacityModule_TABLE.o] Error 1

I am still sticking to master, but this could potentially be a future problem if it gets merged to master.

**Comment by jaharris87** [comment]
loginterpolatesinglevariable_1d3d was removed entirely since it used the old interface.

I have some pending commits in the `amd` branch of thornado that *should* address any missing calls.
is your monte carlo setup in a separate thornado branch?

**Comment by srichers** [comment]
No, I am just using interface_flash_OrderV, in which I use ComputeNeutrinoOpacities_EC_Vector and ComputeNeutrinoOpacities_ES_Vector, both of which use a 4d function. I don't think the 1d3d or 2d2d stuff affects me other than preventing thornado from compiling.

**Comment by jaharris87** [comment]
ok, I am just waiting for `clean_up` to make it into `master`, then I can merge `amd` to `master` in thornado.

**Pull request merged**
