### PR TITLE
make 4D interpolation function public

### PR DESCRIPTION
**Pull request by srichers**

### CODE REVIEW

**Comment by ranchu1** [comment]
The change looks good to me. I will refer to Austin if the routine is ready for GPU uses.

Usually, we pull a feature branch to the `development` branch for conflict test first. Then to the `master` branch.

**Comment by srichers** [comment]
I updated the PR to point to development. Thanks for pointing that out!

**Comment by srichers** [comment]
Although it looks like there were a few commits in master that were not yet in development, so now the PR includes those as well. Let me know if I should create a new branch based on development - would not be hard to do.

**Comment by ranchu1** [comment]
> Although it looks like there were a few commits in master that were not yet in development, so now the PR includes those as well. Let me know if I should create a new branch based on development - would not be hard to do.

Yeah, we do have two or three exceptions for an essential and emergency fix.

**Comment by ranchu1** [comment]
> Although it looks like there were a few commits in master that were not yet in development, so now the PR includes those as well. Let me know if I should create a new branch based on development - would not be hard to do.

You don't need to create a new branch. I looked at the commits that would be merged to the development branch with your edits. I made those cosmetic changes and they are fine.

**Comment by ranchu1** [comment]
@jaharris87  Should we pull it to `master`?

**Comment by jaharris87** [comment]
No opposition from me.

**Comment by ranchu1** [comment]
@srichers I saw you deleted the feature branch. Should I cherry-pick your commit dafa7f43db99a31cc6e485138ed3c1d442480dd8 on master branch? 

Normally, the feature branch will be used to pull into the master branch after being merged to the development branch. Because we don't merge the development branch directly to the master branch.

**Comment by srichers** [comment]
ah, okay. I restored the branch - let me know when it is safe to delete.

**Comment by ranchu1** [comment]
> ah, okay. I restored the branch - let me know when it is safe to delete.

Thank you. I merged it to master and it's safe to delete now.

**Pull request merged**
